# Generated by Django 6.0.4 on 2026-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('point_1', models.CharField(max_length=255)),
                ('point_2', models.CharField(max_length=255)),
                ('point_3', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('image_1', models.ImageField(upload_to='about/')),
                ('image_2', models.ImageField(upload_to='about/')),
                ('image_3', models.ImageField(upload_to='about/')),
                ('image_4', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
