# Generated by Django 6.0.4 on 2026-04-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-quote-left', max_length=50)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
