# Generated by Django 6.0.4 on 2026-04-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
